{-# LANGUAGE DataKinds #-}
{-# OPTIONS_GHC -Wno-orphans #-}

module Cardano.Leios.Types where

import Cardano.Api.Ledger (KeyHash)
import qualified Cardano.Crypto.Hash as Hash
import Cardano.Crypto.Util (SignableRepresentation (..), writeBinaryWord64)
import Cardano.Ledger.Hashes (HASH)
import Cardano.Ledger.Keys (KeyRole (..))
import Data.Word (Word64)

-- | A type that represent the pool ID. This is the blake2b-224 hash of
-- the ed25519 cold key of the stakepool.
type PoolID = KeyHash StakePool

-- | Identifier for the voting round (derived from the slot number of the RB that announced the target EB)
type ElectionID = Word64

instance SignableRepresentation Word64 where
  getSignableRepresentation = writeBinaryWord64

-- | The epoch randomness generated by the Praos slot leader protocol.
type PraosNonce = Word64

-- | Phantom type that represent and EB.
data EndorserBlock

-- | The hash of the EB. Note that `HASH` is a synonym for blake2b_256.
type EndorserBlockHash = Hash.Hash HASH EndorserBlock

-- | A value between zero and one, representing the relative stake
-- A `Party` has in Praos.
type RelativeStake = Rational

-- | The weight we assign each seat in the `CommitteeSelection`
type Weight = Rational
